# Generated by Django 3.2.6 on 2022-08-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=30)),
                ('code', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('disclosure', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
