# Generated by Django 3.2.6 on 2022-08-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
