# Generated by Django 3.2.6 on 2022-08-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disclosure',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
