# Generated by Django 4.0.6 on 2022-08-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('visit', models.IntegerField(default=0)),
                ('current_date', models.DateField(null=True)),
            ],
        ),
    ]
