# Generated by Django 4.0.6 on 2022-08-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_level_problem_problem_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
